max-line-length: 88

bandit:
  run: true

pylint:
  ignored-modules:
    - scipy
  extension-pkg-whitelist:
    - scipy
  ignore-patterns:
    - test_
  disable:
    - unsubscriptable-object
    - invalid-name
    - logging-fstring-interpolation
    - arguments-renamed
    - assignment-from-none
    - unsupported-membership-test
    - cell-var-from-loop
    - broad-except
    - import-outside-toplevel
    - arguments_differ
    - duplicate-code
    - too-many-branches
    - too-many-statements
    - too-many-boolean-expressions
    - R0902
    - R0903
    - R0913
    - R0914
mypy:
  run: true
  ignore_missing_imports: true
  no_strict_optional: true
  ignored-modules: 
    - scipy
  extension-pkg-whitelist:
    - scipy
    - pydantic
  ignore-patterns: 
    - test_