name: testing

on:
  push:

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3

      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('environment.yaml') }}
      - uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: graph-tool
          environment-file: environment.yaml
          use-only-tar-bz2: true

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[strict]
          pip install black prospector[with_mypy]

      - name: Lint with black
        run: |
          black --check --diff --color src/rxn_network

      - name: Lint with prospector
        run: |
          prospector src/rxn_network

  test:
    strategy:
      max-parallel: 6
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3

      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('environment.yaml') }}
      - uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: graph-tool
          environment-file: environment.yaml
          use-only-tar-bz2: true

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[strict,tests]

      - name: Test with pytest
        env:
          MP_API_KEY: ${{ secrets.MP_API_KEY }}
        run: |
          pytest --cov=src/rxn_network --cov-report=xml

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml

  docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3

      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('environment.yaml') }}
      - uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: graph-tool
          environment-file: environment.yaml
          use-only-tar-bz2: true

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[strict,docs]

      - name: Build docs
        run: mkdocs build
